return {
  -- {
  -- "MeanderingProgrammer/render-markdown.nvim",
  -- opts = {
  -- file_types = { "markdown", "Avante" },
  -- },
  -- ft = { "markdown", "Avante" },
  -- },
  -- {
  --   "yetone/avante.nvim",
  --   ---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | string
  --   event = "VeryLazy",
  --   lazy = false,
  --   opts = {
  --     provider = "copilot",
  --     mappings = {
  --       diff = {
  --         ours = "<leader>co",
  --         theirs = "<leader>ct",
  --         all_theirs = "<leader>ca",
  --         both = "<leader>cb",
  --         cursor = "<leader>cc",
  --         next = "]x",
  --         prev = "[x",
  --       },
  --       ask = "<leader>Aa",
  --       edit = "<leader>Ae",
  --       refresh = "<leader>Ar",
  --       toggle = {
  --         default = "<leader>At",
  --         debug = "<leader>Ad",
  --         hint = "<leader>Ah",
  --         suggestion = "<leader>As",
  --       },
  --     },
  --     behaviour = {
  --       auto_suggestions = false,
  --     },
  --     hints = { enabled = false },
  --   },
  --   branch = "main",
  --   -- commit = "ff316f91101fcc328d1e7879ab1bf26a055c2745",
  --   -- if you want to download pre-built binary, then pass source=false. Make sure to follow instruction above.
  --   -- Also note that downloading prebuilt binary is a lot faster comparing to compiling from source.
  --   build = ":AvanteBuild source=false",
  --   dependencies = {
  --     "stevearc/dressing.nvim",
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     --- The below dependencies are optional,
  --     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
  --     -- "zbirenbaum/copilot.lua",   -- for providers='copilot'
  --     {
  --       -- support for image pasting
  --       "HakonHarnes/img-clip.nvim",
  --       event = "VeryLazy",
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to setup it properly if you have lazy=true
  --       "MeanderingProgrammer/render-markdown.nvim",
  --       opts = {
  --         file_types = { "markdown", "Avante" },
  --       },
  --       ft = { "markdown", "Avante" },
  --     },
  --   },
  -- },
}
